import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import { Suspense } from "react";
import LoadingFallback from "@/components/loading-fallback";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import LocaleBootstrapper from "@/components/locale-bootstrapper";
import LocaleGate from "@/components/locale-gate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<LoadingFallback label="Loading" />}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Providers>
              <LocaleBootstrapper />
              <LocaleGate>
                {children}
              </LocaleGate>
            </Providers>
          </NextIntlClientProvider>
        </Suspense>
      </body>
    </html>
  );
}

